In [ ]:
import torch

In [ ]:
y=torch.tensor([[2,3,6,7,4],[3,5,7,9,10],[6,7,8,9,12]])
print(y)
print(y[-2:-1:1,-4:-3:1])

tensor([[ 2,  3,  6,  7,  4],
        [ 3,  5,  7,  9, 10],
        [ 6,  7,  8,  9, 12]])
tensor([[5]])


In [ ]:
import numpy as np



In [ ]:
A=np.random.random((3,3))
B=np.random.random((3,3))
print(X)
print(M)

c=A.T
d=c@A
h=d+B
print(h)

[[0.87466168 0.64626485 0.72331696]
 [0.94368964 0.31050134 0.70510954]
 [0.38086106 0.19666595 0.84246874]]
[[0.19500001 0.1755254  0.31195512]
 [0.10969374 0.20071226 0.39733731]
 [0.23163233 0.11694897 0.7988296 ]]
[[1.15230072 0.92032124 0.63696175]
 [1.56101421 1.61987995 1.4416469 ]
 [0.69926996 0.90633174 0.96897577]]
